### ISSUE TITLE
Create All Galleries Admin View

### ISSUE THREAD

**Issue by memo330179** [BCStudentSoftwareDevTeam/Ullman_Galleries#1]
This is the landing page for the admin. The functionality of this page is as follows
- [ ] Displays all of the galleries in the system
- [ ] Displays the number of submissions the gallery has
- [ ] Displays the status of the gallery 
- [ ] Links to edit page for a single submission
- [ ] Links to the call for submission page

![all_galleries](https://user-images.githubusercontent.com/11654721/34920272-28daa9fa-f93e-11e7-8254-38aaa5639cf1.png)

**Comment by Chauwaj** [comment]
@Jessonsotoventura ,I am still having problems setting up my dev enviroment even after following the instructions. Am getting this error
![image](https://user-images.githubusercontent.com/22758750/35042986-d1358734-fb58-11e7-8fc4-6ec6d52797ec.png)

In meantime, I still went ahead and worked on a few things while am waiting for my dev enviroment to be fixed. (Still placing components where they should be, e.g the create button)
![image](https://user-images.githubusercontent.com/22758750/35042838-1fd35872-fb58-11e7-98b4-37f843bbd043.png)

**Comment by memo330179** [comment]
Hi @Chauwaj, The database has to exist already. Could you share your c9 workspace with me username `memo3301791`?

**Comment by Chauwaj** [comment]
@memo330179  Sure! let me do that now

**Comment by memo330179** [comment]
@Chauwaj the database hasn't been created yet. You should be able to create it and use by:
1. using the mysql command line or phpmyadmin `phpmyadmin-ctl install` to create the database
2. create new user with password or use your c9 username `chauwaj`
3. if using c9 account make sure that the password is an empty string `''`

That should get it to work. Let me know if you have any issues doing this.

**Comment by Chauwaj** [comment]
@memo330179  it works now. Thanks.

**Comment by Jessonsotoventura** [comment]
@Chauwaj  In order to add dummy data, please add it to the scripts/dummy_data.py file and then run python script/dummy_data

You will need to do a pull first

**Comment by Chauwaj** [comment]
@Jessonsotoventura  Thanks for fixing that.

**Comment by Chauwaj** [comment]
@Jessonsotoventura Any ideas why I am getting this error? I am trying to restart the application after doing a pull.

Thanks.

![image](https://user-images.githubusercontent.com/22758750/35200646-1f7a3a54-fee0-11e7-930f-e5732b18aa4d.png)


![image](https://user-images.githubusercontent.com/22758750/35200636-082dea58-fee0-11e7-9d7b-f9b43e11f830.png)

**Comment by Jessonsotoventura** [comment]
@Chauwaj  please pull from development and not master

**Comment by Chauwaj** [comment]
@Jessonsotoventura I pulled from development. Maybe there is something am not doing right.

**Comment by Jessonsotoventura** [comment]
What is the contents of app.py

**Comment by Chauwaj** [comment]
![image](https://user-images.githubusercontent.com/22758750/35200920-e8208e56-fee3-11e7-9c91-2feb0235d3ca.png)

**Comment by Jessonsotoventura** [comment]
Also for a faster reply please contact me on slack

**Comment by memo330179** [comment]
@Chauwaj for this week continue finishing all galleries page. Here is the breakdown of what's left
 -[ ] We need to dynamically get the gallery information from the database.
 -[ ] Dead line open and close should be displayed status - <close-date>
 -[ ] Use bootstrap classes for styling and custom styles should be in `app/static/css/local/<filename>`

**Comment by Chauwaj** [comment]
@memo330179  sure. Just one question, can you elaborate on the second point  "[ ] Dead line open and close should be displayed status ".  Do you mean that the column heading for deadlines should be displayed as "Status"? 

Thanks

**Comment by Jessonsotoventura** [comment]
@Chauwaj  I believe that @memo330179 means that the each entry should have the scheme of depending on its state
```
opens: DATE IT OPENS
closed: DATE IT CLOSED
Active: OPEN Date - CLOSE DATE
```
and that maybe we should rename the deadline field to `status` instead of `deadline`

Also please consider using data tables, it will make sorting the data easier for later use, if you have any questions on datatables feel free to message me

**Comment by Chauwaj** [comment]
@Jessonsotoventura  Thanks. Thats a good idea. This is what I have now. All the information has been pulled from the database.  Does it look like what we want?

![image](https://user-images.githubusercontent.com/22758750/35295007-000216bc-0046-11e8-9045-313761a59c67.png)

**Comment by Jessonsotoventura** [comment]
@chawaj That looks great!
Final note mind including the date in the status field?

So closed would be something like:
```
Closed: 09/27/23
```

**Comment by Chauwaj** [comment]
@Jessonsotoventura  Sure. I will do that. It makes sense to have the dates on there too.

Thanks.

**Comment by Jessonsotoventura** [comment]
@chauwaj Thank you

**Comment by Jessonsotoventura** [comment]
V1 is live thank you for your commits
