### ISSUE TITLE
Create single gallery admin view

### ISSUE THREAD

**Issue by memo330179** [BCStudentSoftwareDevTeam/Ullman_Galleries#3]
This page allows the Admin to see the submissions for a single gallery. Functionality is as follows.
Allows admin to see application

- [ ] Shows name
- [ ] Shows date submitted 
- [ ] Shows status
- [ ] Links application row to single application view
![gallery_admin_view](https://user-images.githubusercontent.com/11654721/34920297-8d014416-f93e-11e7-8d4c-725f8a0424c3.png)

**Comment by Jessonsotoventura** [comment]
V1 is live thank you for your commits
