### ISSUE TITLE
Create Application Page

### ISSUE THREAD

**Issue by memo330179** [BCStudentSoftwareDevTeam/Ullman_Galleries#5]
This page allows a user to submit an application to a gallery.
Functionality is:

- [x] Shows gallery name
- [x] Requests first name
- [x] Requests last name
- [x] Requests address, zip, state
- [x] Requests email
- [x] Requests phone number
- [x] Request personal website
- [x] Requests and uploads cv and personal statement
- [x] Requests and uploads images
- [ ] Save application

![gallery_application](https://user-images.githubusercontent.com/11654721/34920316-fc4d3212-f93e-11e7-9be8-edd71a7ab015.png)

**Comment by memo330179** [comment]
For Sprint 2 let's save this information in the database. For images and other files, you can include hard-coded links. In other words, don't worry about file uploads if it turns into a larger issue.

**Comment by Jessonsotoventura** [comment]
V1 is live thank you for your commits
