### ISSUE TITLE
Create Application Review Page

### ISSUE THREAD

**Issue by memo330179** [BCStudentSoftwareDevTeam/Ullman_Galleries#6]
This page allows a user to review the contents of the application they submitted 
Functionality is:

- [x] Display Gallery name
- [x] Display first name of applicant
- [x] Display last name of applicant
- [x] Display email of applicant
- [x] Display address, zip, state of applicant
- [x] Display phone number of applicant
- [x] Link to applicant’s personal site
- [ ] Allow download of applicant’s cv and personal statement
- [ ] Display preview of all images
- [ ] Allow download of all images  
- [ ] Submit application

![application_review](https://user-images.githubusercontent.com/11654721/34920357-6d6a259a-f93f-11e7-9197-f59c9fbecac4.png)

**Comment by memo330179** [comment]
Let's grab the data from the database during sprint2

**Comment by Jessonsotoventura** [comment]
Good job!
- Now let's see if we can add a button to download the cv and artist statement. 
- Also we need a way of displaying the images uploaded by a user, I have this idea:
  * A grid of 3x3 or whatever that scrolls and when you click on an image it expands it in a modal like fashion. That's only my idea, implement it however you want. 
  * Also maybe check to see if a library already exists that does this, I feel like one should but I don't know for sure.

**Comment by Jessonsotoventura** [comment]
V1 is live thank your for your commits

**Comment by Jessonsotoventura** [comment]
V1 is live thank your for your commits
